### ISSUE TITLE
Missing relationship between customer and order

### ISSUE THREAD

**Issue by emmbyiringiro** [zandoan/turing-mobile#4]
![customer-order-relationship-missing](https://user-images.githubusercontent.com/46843540/58188117-585fa280-7cb8-11e9-92b8-1568c3b1037f.PNG)
 
How can I assign a customer with #customer_id to order with #order_id ? 

I don't find that relationship.

**Comment by TuringCom** [comment]
You don't need to worry about orders of a specific customer.
