### ISSUE TITLE
JsonWebTokenError: invalid signature

### ISSUE THREAD

**Issue by emmbyiringiro** [zandoan/turing-mobile#8]
I do challenge with React Native and I had  integrated Login/SignUp functionality and working perfectly. When customer login successfully server return JWToken  to authenticate user later. I store JWToken on device use React Native Async Storage. unfortunately, when I retrieve saved token and use it to update customer information , server return **invalid signature error.**

I try also to manually copy token and paste in backend api playground and it's still  invalid.

 Happy to hear back from you

**Comment by edertaveiraturing** [comment]
Hi @emmbyiringiro, only on the update customer endpoint, or on all of these?

**Comment by emmbyiringiro** [comment]
I tried on update customer address and fail , here example

https://repl.it/@EmmanuelBYIRING/APi-Call-Pyaground

**Comment by emmbyiringiro** [comment]
Here how I get JWToken 
https://repl.it/@EmmanuelBYIRING/Login-With-Api-Call

I want to use returned token to update customer address then fail.

**Comment by edertaveiraturing** [comment]
So, I did a test here using a new user and a new user-key, it's work.

**Comment by emmbyiringiro** [comment]
It work when you login via backed UI login form then use returned token but have you return it with  Fetch or Axios Api.

example:

`login = async () => {
    fetch('https://backendapi.turing.com/customers/login', {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({email: "EMAIL", password: "PASSWORD"})
    })
      .then((response) => response.json())
      .then((responseJson) => {
        //do something
        console.log(responseJson);
      })
      .catch((error) => {
        console.error(error);
      });
  }	

  login() `

This where issue raised when raised

**Comment by emmbyiringiro** [comment]
Dear @edertaveiraturing , Thanks for support, I have confusing with Root backend  :)

I use https://**backendapi**.turing.com/customer/login  as backend root for login   instead https://**mobilebackend**.turing.com/customers/login .

Can you please update example in readme file for Mobile Challenge... I follow example there which result in this error
